services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8080
    volumes:
      - ./config:/config
      - /data/downloads:/downloads
    restart: unless-stopped
    networks:
      - proxy-network

  qui:
    image: ghcr.io/autobrr/qui:latest
    container_name: qui
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./qui:/config
      - /data/downloads:/downloads
    restart: unless-stopped
    networks:
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qui.rule=Host(`torrent.desktop.madhur.co.in`)"
      - "traefik.http.routers.qui.entrypoints=websecure"
      - "traefik.http.services.qui.loadbalancer.server.port=7476"
      - "traefik.http.routers.qui.tls.certresolver=letencrypt"
      - "traefik.docker.network=proxy-network"
      - "traefik.http.routers.qui.middlewares=vpn-whitelist"

networks:
  proxy-network:
    external: true
