services:
  gatus:
    image: ghcr.io/twin/gatus:latest
    container_name: gatus
    restart: unless-stopped
    volumes:
      - ./config:/config
    networks:
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gatus.rule=Host(`gatus.desktop.madhur.co.in`)"
      - "traefik.http.routers.gatus.entrypoints=websecure"
      - "traefik.http.routers.gatus.tls.certresolver=letencrypt"
      - "traefik.http.services.gatus.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy-network"

networks:
  proxy-network:
    external: true
