
services:
  app:
    image: lissy93/networking-toolbox:latest
    container_name: networkingtoolbox
    # ports:
    #   - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      disable: true
    networks:
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.networktoolbox.rule=Host(`nt.desktop.madhur.co.in`)"
      - "traefik.http.routers.networktoolbox.entrypoints=websecure"
      - "traefik.http.routers.networktoolbox.tls.certresolver=letencrypt"
      - "traefik.http.services.networktoolbox.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy-network"
      - "traefik.http.routers.networktoolbox.middlewares=vpn-whitelist@docker"

networks:
  proxy-network:
    external: true
