services:
  tube:
    image: prologic/tube
    container_name: tube
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - /data:/data
      - ./config.json:/config.json:ro
    restart: unless-stopped
    networks:
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tube.rule=Host(`tube.desktop.madhur.co.in`)"
      - "traefik.http.routers.tube.entrypoints=websecure"
      - "traefik.http.services.tube.loadbalancer.server.port=8000"
      - "traefik.http.routers.tube.tls.certresolver=letencrypt"
      - "traefik.docker.network=proxy-network"

networks:
  proxy-network:
    external: true
