services:
  server:
    image: ghcr.io/goauthentik/server:2026.2.1
    container_name: authentik-server
    restart: unless-stopped
    command: server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      AUTHENTIK_REDIS__HOST: host.docker.internal
      AUTHENTIK_POSTGRESQL__HOST: host.docker.internal
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRESQL__PASSWORD}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    networks:
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentik.rule=Host(`authentik.desktop.madhur.co.in`)"
      - "traefik.http.routers.authentik.entrypoints=websecure"
      - "traefik.http.routers.authentik.tls.certresolver=letencrypt"
      - "traefik.http.services.authentik.loadbalancer.server.port=9000"
      - "traefik.docker.network=proxy-network"

  worker:
    image: ghcr.io/goauthentik/server:2026.2.1
    container_name: authentik-worker
    restart: unless-stopped
    command: worker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      AUTHENTIK_REDIS__HOST: host.docker.internal
      AUTHENTIK_POSTGRESQL__HOST: host.docker.internal
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRESQL__PASSWORD}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./custom-templates:/templates
      - ./certs:/certs
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
