services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./config:/config
      - /data/downloads:/media  # Adjust this path to where your media is stored
      - /home/madhur/Videos:/media4  # Adjust this path to where your media is stored
      - /home/madhur/Screenshots/Timeline:/media2  # Adjust this path to where your media is stored
      - /data/be_discussions:/media3  # Adjust this path to where your media is stored      - ./cache:/cache
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video]
    networks:
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jf.desktop.madhur.co.in`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.jellyfin.tls.certresolver=letencrypt"
      - "traefik.docker.network=proxy-network"

networks:
  proxy-network:
    external: true
