services:
  booklore:
    image: booklore/booklore:latest
    container_name: booklore
    environment:
      - APP_USER_ID=1000
      - APP_GROUP_ID=1000
      - TZ=Asia/Kolkata
      - BOOKLORE_PORT=6060
      - DATABASE_URL=jdbc:mariadb://booklore_db:3306/booklore
      - DATABASE_USERNAME=booklore
      - DATABASE_PASSWORD=booklore123
    volumes:
      - ./data:/app/data
      - ./books:/books
      - ./bookdrop:/bookdrop
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.booklore.rule=Host(`booklore.desktop.madhur.co.in`)"
      - "traefik.http.routers.booklore.entrypoints=websecure"
      - "traefik.http.services.booklore.loadbalancer.server.port=6060"
      - "traefik.http.routers.booklore.tls.certresolver=letencrypt"
      - "traefik.docker.network=proxy-network"
      - "traefik.http.routers.booklore.middlewares=vpn-whitelist"
      - "traefik.http.middlewares.vpn-whitelist.ipwhitelist.sourcerange=10.42.42.0/24,192.168.1.0/24"
    networks:
      - proxy-network
    ports:
      - 6060:6060
    restart: unless-stopped
    depends_on:
      booklore_db:
        condition: service_healthy

  booklore_db:
    image: lscr.io/linuxserver/mariadb:11.4.5
    container_name: booklore_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - MYSQL_ROOT_PASSWORD=booklore_root_123
      - MYSQL_DATABASE=booklore
      - MYSQL_USER=booklore
      - MYSQL_PASSWORD=booklore123
    volumes:
      - ./mariadb:/config
    networks:
      - proxy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  proxy-network:
    external: true
